import Head from "next/head";
import * as React from "react";
import { Component } from "react";

interface HeadAppProps {}

interface HeadAppState {}

class HeadApp extends Component<HeadAppProps, HeadAppState> {
  state = {};
  render() {
    return (
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    );
  }
}

export default HeadApp;
